### PR TITLE
Add customer service

### PR DESCRIPTION
**Pull request by robwittman**
Adds customer API for #29

---
This change is [Reviewable](https://reviewable.io/reviews/nozzlegear/shopify-prime/35)

### CODE REVIEW

**Comment by nozzlegear** [comment]
This looks awesome! One quick request, could you change the services/customer.ts file name to services/customers.ts?

**Comment by robwittman** [comment]
@nozzlegear File name updated. Also added a missing `.json`, but its weird the request was working as it was 🤷‍♂

**Comment by robwittman** [comment]
@nozzlegear Can you take another look at this? Thanks!

**Comment by nozzlegear** [comment]
Sure, sorry about that! I'll merge and publish this on Monday when I've got some time for open source work scheduled.

**Comment by nozzlegear** [comment]
Published! Thank you very much for pull request, sorry it took so long to get it merged in.

**Pull request merged**
