### PR TITLE
Added refunds and price rule apis

### PR DESCRIPTION
**Pull request by dcworldwide**
Included price rule tests.

### CODE REVIEW

**Comment by nozzlegear** [comment]
Thanks for the pull request! I had to skip the price rules tests because they were failing on the CI build without a Shopify Plus store. 

Your changes should be available on NPM with version 2.4.0.

**Comment by dcworldwide** [comment]
Thanks!

Actually they are a new non plus apI just released.

**Comment by nozzlegear** [comment]
Oh I see that now, I was getting 403 forbidden errors and just figured it was because the Price Rules were only for Plus accounts or something. I'll have to look closer!

**Comment by nozzlegear** [comment]
I finally figured out why the price rules tests are failing. When trying to create a price rule, Shopify is returning an error that says **"[API] This action requires merchant approval for write_price_rules scope."**. It looks like Shopify has made a change to private apps; where previously they had automatic access to all scopes, merchants must now give them specific scopes. Old private apps get grandfathered in and keep access to all previous scopes, but new scopes (like the price rules scope) must be turned on by the merchant.

**Comment by dcworldwide** [comment]
Ah that makes sense. I had to uninstall my apps then explicitly request the new scopes as well. 

It's a little ugly the way they've preserved the old discount api but I imagine it won't be deprecated for some time.

**Pull request merged**
