### PR TITLE
Locations, InventoryLevels, InventoryItems and Fulfillment Support

### PR DESCRIPTION
**Pull request by jdalrymple**
Due to the recent changes to the Shopify API, I've added support for these three services. 

For more information about these changes see: https://help.shopify.com/api/guides/inventory-migration-guide

### CODE REVIEW

**Comment by jdalrymple** [comment]
Noticed some weird things in the PR, will close and recreate

**Comment by jdalrymple** [comment]
Not sure whats up exactly, but looking over the commits, it looks fine. If something is off, just point it out and ill fix it

**Comment by jdalrymple** [comment]
Going to verify fulfillments tonight! hold off on the merge please :D

**Comment by nozzlegear** [comment]
Sure! Let me know when it's ready.




--


Josh Harms







On Fri, Jun 1, 2018 at 2:42 PM -0500, "jdalrymple" <notifications@github.com> wrote:












Going to verify fulfillments tonight! hold off on the merge please :D

**Comment by jdalrymple** [comment]
Should be good now!

**Comment by nozzlegear** [comment]
Great! I should have time to merge tomorrow, please feel free to ping me if I don't get to it!




--


Josh Harms







On Thu, Jun 7, 2018 at 8:01 AM -0500, "jdalrymple" <notifications@github.com> wrote:












Should be good now!

**Comment by jdalrymple** [comment]
Any updates :)

**Comment by nozzlegear** [comment]
Ha, sorry! I don't mean to ignore these, I blame GitHub for not showing open pull requests or issues like it used to. 😉 This is published on NPM in version 2.8.0, thank you very much for the contributions!

**Pull request merged**
