### PR TITLE
Fixed Fulfillment Support and Added Product Variant Support

### PR DESCRIPTION
**Pull request by jdalrymple**
After more testing i found some serious bugs with the fulfillments support added in the last PR. Fixed them in this one! Please give it a once over to make sure i didnt miss anything.

### CODE REVIEW

**Comment by nozzlegear** [comment]
Ha, I wish I would have seen this just 30 seconds ago before I published 2.6.0! I'll look it over as soon as I get a chance.

**Comment by jdalrymple** [comment]
:( Sorry

**Comment by nozzlegear** [comment]
Sorry, I let this get away from me! I see you've added some commits, is this still ready to merge?

**Comment by jdalrymple** [comment]
Yup I added variants as well. I'll do more testing today to ensure things are on point, but should be good by tomorrow :)

**Comment by jdalrymple** [comment]
Any chance this PR could be accepted ?

**Comment by nozzlegear** [comment]
Sorry, I dropped the ball on this. Your changes should be published in NPM in version 2.7.0. Thank you!

**Comment by jdalrymple** [comment]
Thanks!

**Pull request merged**
